'use strict';
// Historical exploration seed retained for provenance; sunrise/sunset art direction supersedes its window motif. No runtime randomness.
const DESIGN_SEED = 2057000771;
const now=()=>new Date(), motion=matchMedia('(prefers-reduced-motion: reduce)');
let animations=[],screen='intro',tick,night=false,geoRequest=0,lastToggle=-Infinity;
const sample={lat:29.4241,lng:-98.4936,sample:true};
let place=LS.get('place',sample);
if(!place||!Number.isFinite(place.lat)||!Number.isFinite(place.lng)||Math.abs(place.lat)>90||Math.abs(place.lng)>180)place=sample;
function cancelMotion(){animations.forEach(a=>a.cancel());animations=[];}
function animate(el,frames,options){if(motion.matches||document.hidden)return;const a=el.animate(frames,options);animations.push(a);a.finished.then(()=>{animations=animations.filter(x=>x!==a);}).catch(()=>{});return a;}
function trace(){cancelMotion();if(motion.matches)return;
 animate(document.querySelector('.light-wash'),[{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:1400,fill:'backwards',easing:'cubic-bezier(.2,.6,.2,1)'});
 animate(document.querySelector('.light-track'),[{transform:'scaleX(0)'},{transform:'scaleX(1)'}],{duration:1300,delay:180,fill:'backwards',easing:'cubic-bezier(.22,.8,.24,1)'});
 animate(document.querySelector('#marker i'),[{opacity:0},{opacity:1}],{duration:420,delay:1100,fill:'backwards'});
 animate(document.querySelector('.sun-labels'),[{opacity:0},{opacity:1}],{duration:400,delay:1000,fill:'backwards'});
 animate(document.querySelector('.sun-event.rising'),[{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:800,delay:350,fill:'backwards',easing:'cubic-bezier(.2,.6,.2,1)'});
 animate(document.querySelector('.sun-event.setting'),[{opacity:0,transform:'translateY(-5px)'},{opacity:1,transform:'translateY(0)'}],{duration:800,delay:700,fill:'backwards',easing:'cubic-bezier(.2,.6,.2,1)'});
}
function setScreen(next){screen=next;for(const id of ['intro','home','learn']){$(id).hidden=id!==next;$(id).inert=id!==next;}$('skip').hidden=next!=='intro';$('learn-open').hidden=next!=='home';}
function openDay(withMotion=true){if(screen!=='intro')return;const pane=$('light-window'),before=pane.getBoundingClientRect(),beforeTrack=document.querySelector('.light-track').getBoundingClientRect();cancelMotion();LS.set('introduced',true);setScreen('home');$('home-slot').append(pane);pane.removeAttribute('aria-hidden');render();window.scrollTo(0,0);const after=pane.getBoundingClientRect();$('today-title').focus({preventScroll:true});if(withMotion&&!motion.matches){animate(pane,[{transform:`translate(${before.x-after.x}px,${before.y-after.y}px) scale(${before.width/after.width},${before.height/after.height})`},{transform:'translate(0,0) scale(1,1)'}],{duration:540,easing:'cubic-bezier(.2,.8,.2,1)'});// Preserve the horizontal path's vertical position through the pane resize.
 // Read final layout without the pane's running transform.
 const localTrack=document.querySelector('.window-inner').offsetTop+document.querySelector('.timeline').offsetTop+44;
 const offset=(beforeTrack.top-before.top)/(before.height/after.height)-localTrack;
 animate(document.querySelector('.timeline'),[{transform:`translateY(${offset}px)`},{transform:'translateY(0)'}],{duration:540,easing:'cubic-bezier(.2,.8,.2,1)'});
 // Keep data unscaled: labels only appear after the shared material lands.
 for(const selector of ['.day-meta','.sun-labels','#marker-label'])animate(document.querySelector(selector),[{opacity:0},{opacity:1}],{duration:180,delay:540,fill:'backwards'});
 for(const el of document.querySelectorAll('#home-slot ~ *'))animate(el,[{opacity:0},{opacity:1}],{duration:180,delay:540,fill:'backwards'});}}
function replay(){cancelMotion();$('intro-slot').append($('light-window'));$('light-window').setAttribute('aria-hidden','true');setScreen('intro');window.scrollTo(0,0);$('welcome-title').focus({preventScroll:true});trace();}
function clock(ms){const s=Math.floor(Math.max(0,ms)/1000),h=Math.floor(s/3600);return(h?h+':':'')+String(Math.floor(s/60)%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function duration(m){return m>0&&m<1?'<1 min':Math.floor(m)+' min';}
function solar(){const d=new Date(),t=sunTimes(place.lat,place.lng,d);$('date').textContent=d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});$('sunrise').textContent=fmtTime(t.sunrise);$('sunset').textContent=fmtTime(t.sunset);const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;$('solar-note').textContent='Estimated times · '+zone+' (device time)';$('location').replaceChildren(document.createTextNode(place.sample?'San Antonio':'Current location'));const detail=document.createElement('span');detail.textContent=place.sample?'Sample location · Change ↗':'Change location ↗';$('location').append(detail);
 const pane=$('light-window');
 if(t.sunrise&&t.sunset){const min=Math.round((t.sunset-t.sunrise)/60000),p=(d-t.sunrise)/(t.sunset-t.sunrise),clamped=Math.max(0,Math.min(1,p));night=p<0||p>1;$('day-length').textContent=Math.floor(min/60)+'h '+min%60+'m';pane.style.setProperty('--day-position',clamped*100+'%');pane.dataset.polar='';pane.dataset.period=p<0?'before':p>1?'after':'day';$('marker-label').textContent=p<0?'Before sunrise':p>1?'After sunset':'Now';$('marker').dataset.edge=p<.15?'start':p>.85?'end':'';
 }else{night=t.polar==='night';pane.dataset.polar=night?'night':'day';pane.dataset.period=night?'polar-night':'polar-day';$('day-length').textContent=night?'No sunrise':'All-day daylight';$('marker-label').textContent=night?'No sunrise today':'No sunset today';$('marker').dataset.edge='';pane.style.setProperty('--day-position','50%');}}

function render(){solar();const active=!!getSession();document.body.classList.toggle('running',active);$('timer').hidden=!active;$('timer').textContent=clock(sessionElapsedMs());$('action-label').textContent=active?'Stop & log':'Start timer';$('action-symbol').textContent=active?'□':'↗';$('phase').textContent=active?'Timer running':'Time outside';$('session-title').textContent=active?'Less screen. More sky.':$('light-window').dataset.period==='before'?'Sunrise is coming.':night?($('light-window').dataset.period==='polar-night'?'No sunrise today.':'The sun’s down.'):'Step outside.';$('session-copy').textContent=active?'The timer keeps running when you put your phone away.':$('light-window').dataset.period==='before'?'Check the sunrise time above and plan your morning outside.':night?'You can still use the timer to log time outside.':'Take a walk or your next break outdoors.';$('total').textContent=duration(todaySunTotal());$('storage-note').hidden=!storageFailed;if($('records').open)history();}
function history(){const days=ledger().days,list=$('history');list.replaceChildren();for(let n=0;n<7;n++){const d=new Date();d.setDate(d.getDate()-n);const li=document.createElement('li'),a=document.createElement('span'),b=document.createElement('span');a.textContent=n===0?'Today':d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});const total=record(days[dayKey(d)]).total;b.textContent=Number.isFinite(total)&&total>0?duration(total):'No time logged';li.append(a,b);list.append(li);}}
$('open-day').onclick=()=>openDay();$('skip').onclick=()=>openDay(false);$('replay').onclick=replay;
$('toggle').onclick=()=>{const t=performance.now();if(t-lastToggle<450)return;lastToggle=t;cancelMotion();if(getSession()){const m=stopSession();$('status').textContent=(storageFailed?'Kept for this visit: ':'Session logged: ')+clock(m*60000)+'.';}else{startSession();$('status').textContent='Timer started.';}render();};
$('learn-open').onclick=()=>{cancelMotion();setScreen('learn');$('learn-title').focus();window.scrollTo(0,0);};$('learn-back').onclick=()=>{setScreen('home');render();$('learn-open').focus();};$('records').ontoggle=history;
$('location').onclick=()=>{cancelMotion();$('place-dialog').showModal();$('close').focus();};$('close').onclick=()=>$('place-dialog').close();$('place-dialog').onclose=()=>{geoRequest++;$('use-location').disabled=false;$('location').focus();};
// Keep a full keyboard cycle inside the native modal, including Chromium's document boundary.
$('place-dialog').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=[...$('place-dialog').querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&(document.activeElement===first||!$('place-dialog').contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!$('place-dialog').contains(document.activeElement))){e.preventDefault();first.focus();}});
$('use-sample').onclick=()=>{place={...sample};LS.set('place',place);render();$('place-dialog').close();};
$('use-location').onclick=()=>{if(!navigator.geolocation){$('location-status').textContent='This browser can’t find your location. Use the San Antonio example instead.';return;}const request=++geoRequest;$('use-location').disabled=true;$('location-status').textContent='Finding your location… Allow access if your browser asks.';navigator.geolocation.getCurrentPosition(position=>{if(request!==geoRequest)return;place={lat:position.coords.latitude,lng:position.coords.longitude,sample:false};LS.set('place',place);$('use-location').disabled=false;render();$('place-dialog').close();},error=>{if(request!==geoRequest)return;$('use-location').disabled=false;$('location-status').textContent=error.code===1?'Location access denied. Allow it in browser settings, or use the example.':error.code===3?'Location request timed out. Try again or use the example.':'Couldn’t find your location. Try again or use the example.';},{enableHighAccuracy:false,timeout:8000,maximumAge:300000});};
motion.addEventListener('change',cancelMotion);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&screen==='intro')openDay(false);});
function visibility(){clearInterval(tick);cancelMotion();if(!document.hidden){render();tick=setInterval(render,1000);}}
document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',cancelMotion);window.addEventListener('pageshow',()=>render());
if(LS.get('introduced',false)){setScreen('home');$('home-slot').append($('light-window'));$('light-window').removeAttribute('aria-hidden');}else setScreen('intro');visibility();if(screen==='intro')trace();
